
java_library(name = "wpt",
  srcs = glob(["*.java"]),
  deps = [
    '//java/client/src/org/openqa/selenium:selenium',
    '//java/client/src/org/openqa/selenium/remote:remote',
    '//third_party/java/gson:gson',
    '//third_party/java/guava:guava',
    '//third_party/java/httpcomponents:httpclient'
  ],
  visibility = [
    '//java/server/src/...'
  ]
 )
